package br.jus.tjpa.siga;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * AutenticacaoWSService service = new AutenticacaoWSService();
 * AutenticacaoWS portType = service.getAutenticacaoWSPort();
 * portType.autenticar(...);
 * </pre>
 * 
 * </p>
 * 
 */

@WebServiceClient(name = "AutenticacaoWSService", targetNamespace = "http://autenticacao.tjpa.jus.br/", wsdlLocation = "https://wsauth.i.tj.pa.gov.br/autenticacaoTJ/autenticacao?wsdl")
public class AutenticacaoWSService extends Service {

	private final static URL AUTENTICACAOWSSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(br.jus.tjpa.siga.AutenticacaoWSService.class
					.getName());
	static {
		URL url = null;
				
		HttpsTrustManager.allowAllSSL();
		
		try {
			URL baseUrl;
			baseUrl = br.jus.tjpa.siga.AutenticacaoWSService.class
					.getResource(".");
			url = new URL(baseUrl,
					"https://wsauth.i.tj.pa.gov.br/autenticacaoTJ/autenticacao?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'https://wsauth.i.tj.pa.gov.br/autenticacaoTJ/autenticacao?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		AUTENTICACAOWSSERVICE_WSDL_LOCATION = url;
	}

	public AutenticacaoWSService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public AutenticacaoWSService() {
		super(AUTENTICACAOWSSERVICE_WSDL_LOCATION, new QName(
				"http://autenticacao.tjpa.jus.br/", "AutenticacaoWSService"));
	}

	/**
	 * 
	 * @return returns AutenticacaoWS
	 */
	@WebEndpoint(name = "AutenticacaoWSPort")
	public AutenticacaoWS getAutenticacaoWSPort() {
		return super.getPort(new QName("http://autenticacao.tjpa.jus.br/",
				"AutenticacaoWSPort"), AutenticacaoWS.class);
	}

}
