package br.jus.tjpa.siga;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "AutenticacaoWS", targetNamespace = "http://autenticacao.tjpa.jus.br/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AutenticacaoWS {

	/**
	 * 
	 * @param usuario
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(name = "autenticarResponse", targetNamespace = "http://autenticacao.tjpa.jus.br/", partName = "autenticarResponse")
	public String autenticar(
			@WebParam(name = "usuario", targetNamespace = "http://autenticacao.tjpa.jus.br/", partName = "usuario")
			UsuarioWS usuario);

}
